# Generated by Django 3.1 on 2020-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=10, verbose_name='IBAN')),
                ('city', models.CharField(max_length=50, verbose_name='City name')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tax rate')),
            ],
        ),
    ]
