# Generated by Django 3.1 on 2020-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20200910_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tax amount'),
        ),
    ]
