# Generated by Django 3.1 on 2020-09-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxmodel',
            options={'get_latest_by': 'valid_from'},
        ),
    ]
