# Generated by Django 3.1 on 2020-09-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_data', '0002_auto_20200919_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributionsmodality',
            old_name='pension_fund_one',
            new_name='pension_fund_gen',
        ),
        migrations.RenameField(
            model_name='contributionsmodality',
            old_name='pension_fund_two',
            new_name='pension_fund_ind',
        ),
        migrations.RemoveField(
            model_name='taxmodel',
            name='lo_tax_bracket',
        ),
        migrations.AddField(
            model_name='hourfund',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Year'),
        ),
    ]
