# Generated by Django 3.1 on 2020-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=20)),
                ('street_number', models.IntegerField()),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=20)),
                ('street_number', models.IntegerField()),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
