# Generated by Django 3.1 on 2020-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Contract ID')),
                ('contract_type', models.CharField(max_length=100, unique=True, verbose_name='Contract type')),
                ('contract_description', models.CharField(max_length=255, verbose_name='Contract description')),
                ('contract_retired', models.BooleanField(default=False, verbose_name='Contract retired')),
            ],
        ),
    ]
