# Generated by Django 3.1 on 2020-09-12 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiration date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
