# Generated by Django 3.1 on 2020-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place_name', models.CharField(max_length=50, verbose_name='Work place name')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Gross salary')),
            ],
        ),
    ]
