# Generated by Django 3.1 on 2020-09-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '__first__'),
        ('work_places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkPlaces',
            new_name='WorkPlace',
        ),
    ]
